name: Packaging CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo ::set-output name=version::${VERSION}
      - name: Build wheel
        run: |
          sudo apt update
          sudo apt install python3-setuptools python3-wheel
          python3 setup.py bdist_wheel
      - name: Build snap
        run: |
          sudo snap install snapcraft --classic
          snapcraft --destructive-mode
      - name: Build flatpak
        run: |
          sudo apt install flatpak flatpak-builder --fix-missing
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6 -y --noninteractive --user
          flatpak-builder build-dir org.flatpak.PackagingDemo.yml --force-clean
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload wheel
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist/packaging_demo-${{ steps.version.outputs.version }}-py3-none-any.whl
          asset_name: chimp.whl
          asset_content_type: application/zip
      - name: Upload Snap
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./snap-demo_${{ steps.version.outputs.version }}_amd64.snap
          asset_name: linux-packaging.snap
          asset_content_type: application/vnd.snap
      - name: Upload flatpak
        continue-on-error: true
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./snap-demo_${{ steps.version.outputs.version }}_amd64.snap
          asset_name: linux-packaging.snap
          asset_content_type: application/vnd.snap
